services:
    postgres:
        image: postgres:14.2-alpine
        environment:
            - POSTGRES_PASSWORD=supersecurepassword
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - "boolean-data:/var/lib/postgresql/data/pgdata"
    boolean:
        build: .
        env_file:
            - .env
        links:
            - postgres
volumes:
    boolean-data: {}
